-- Bimbel Juara CBT bank-soal schema
-- Fokus: multi-role CBT, assignment, hasil ujian, settings global, dan audit log.
-- Jalankan di Supabase SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  username text not null unique,
  full_name text,
  class_name text,
  role text not null default 'student' check (role in ('superadmin', 'admin', 'student')),
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists full_name text,
  add column if not exists class_name text,
  add column if not exists role text not null default 'student',
  add column if not exists is_active boolean not null default true,
  add column if not exists last_login_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  alter table public.profiles
    add constraint profiles_role_check check (role in ('superadmin', 'admin', 'student'));
exception
  when duplicate_object then null;
end $$;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.categories
  add column if not exists name text,
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

create table if not exists public.question_packages (
  id bigint generated by default as identity primary key,
  title text not null,
  category_id bigint not null references public.categories (id) on delete restrict,
  description text,
  duration_minutes integer not null default 60 check (duration_minutes > 0),
  passing_score integer not null default 70 check (passing_score >= 0),
  is_published boolean not null default false,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (title, category_id)
);

alter table public.question_packages
  add column if not exists title text,
  add column if not exists category_id bigint,
  add column if not exists description text,
  add column if not exists duration_minutes integer,
  add column if not exists passing_score integer,
  add column if not exists is_published boolean,
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.question_packages (id) on delete cascade,
  category_id bigint references public.categories (id) on delete set null,
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null check (correct_option in ('A', 'B', 'C', 'D')),
  explanation text,
  points integer not null default 1 check (points > 0),
  order_index integer not null default 1 check (order_index > 0),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (package_id, order_index)
);

alter table public.questions
  add column if not exists package_id bigint,
  add column if not exists category_id bigint,
  add column if not exists question_text text,
  add column if not exists option_a text,
  add column if not exists option_b text,
  add column if not exists option_c text,
  add column if not exists option_d text,
  add column if not exists correct_option char(1),
  add column if not exists explanation text,
  add column if not exists points integer,
  add column if not exists order_index integer,
  add column if not exists created_by uuid,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.question_packages (id) on delete cascade,
  assigned_by uuid references public.profiles (id) on delete set null,
  assigned_to_user uuid references public.profiles (id) on delete cascade,
  assigned_to_class text,
  available_from timestamptz,
  due_at timestamptz,
  status text not null default 'active' check (status in ('active', 'paused', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (assigned_to_user is not null or assigned_to_class is not null)
);

alter table public.assignments
  add column if not exists package_id bigint,
  add column if not exists assigned_by uuid,
  add column if not exists assigned_to_user uuid,
  add column if not exists assigned_to_class text,
  add column if not exists available_from timestamptz,
  add column if not exists due_at timestamptz,
  add column if not exists status text,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  assignment_id bigint references public.assignments (id) on delete set null,
  package_id bigint not null references public.question_packages (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'in_progress' check (status in ('in_progress', 'submitted', 'cancelled')),
  total_questions integer not null default 0 check (total_questions >= 0),
  correct_count integer not null default 0 check (correct_count >= 0),
  score numeric(10, 2) not null default 0,
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.attempts
  add column if not exists assignment_id bigint,
  add column if not exists package_id bigint,
  add column if not exists user_id uuid,
  add column if not exists status text,
  add column if not exists total_questions integer,
  add column if not exists correct_count integer,
  add column if not exists score numeric(10, 2),
  add column if not exists started_at timestamptz,
  add column if not exists submitted_at timestamptz,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

create table if not exists public.attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.attempts (id) on delete cascade,
  question_id bigint not null references public.questions (id) on delete cascade,
  selected_option char(1),
  is_correct boolean not null default false,
  points_awarded integer not null default 0,
  created_at timestamptz not null default now(),
  unique (attempt_id, question_id)
);

alter table public.attempt_answers
  add column if not exists attempt_id bigint,
  add column if not exists question_id bigint,
  add column if not exists selected_option char(1),
  add column if not exists is_correct boolean,
  add column if not exists points_awarded integer,
  add column if not exists created_at timestamptz;

create table if not exists public.system_settings (
  key text primary key,
  value text not null,
  updated_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.system_settings
  add column if not exists key text,
  add column if not exists value text,
  add column if not exists updated_by uuid,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles (id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_logs
  add column if not exists actor_id uuid,
  add column if not exists action text,
  add column if not exists entity_type text,
  add column if not exists entity_id text,
  add column if not exists summary text,
  add column if not exists metadata jsonb,
  add column if not exists created_at timestamptz;

create or replace function public.is_admin_like()
returns boolean
language sql
stable
as $$
  select coalesce(
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role in ('admin', 'superadmin')
    ),
    false
  );
$$;

create or replace function public.is_superadmin()
returns boolean
language sql
stable
as $$
  select coalesce(
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'superadmin'
    ),
    false
  );
$$;

create or replace function public.student_package_access(target_package_id bigint)
returns boolean
language sql
stable
as $$
  select coalesce(
    public.is_admin_like()
    or exists (
      select 1
      from public.assignments a
      left join public.profiles p on p.id = auth.uid()
      where a.package_id = target_package_id
        and a.status = 'active'
        and (
          (a.assigned_to_user is not null and a.assigned_to_user = auth.uid())
          or (
            a.assigned_to_class is not null
            and p.class_name is not null
            and lower(a.assigned_to_class) = lower(p.class_name)
          )
        )
        and (a.available_from is null or a.available_from <= now())
        and (a.due_at is null or a.due_at >= now())
    ),
    false
  );
$$;

create or replace function public.student_question_access(target_package_id bigint)
returns boolean
language sql
stable
as $$
  select coalesce(
    public.is_admin_like()
    or public.student_package_access(target_package_id),
    false
  );
$$;

create index if not exists idx_questions_package_id on public.questions (package_id);
create index if not exists idx_assignments_package_id on public.assignments (package_id);
create index if not exists idx_assignments_user_id on public.assignments (assigned_to_user);
create index if not exists idx_attempts_user_id on public.attempts (user_id);
create index if not exists idx_attempts_package_id on public.attempts (package_id);
create index if not exists idx_audit_logs_actor_id on public.audit_logs (actor_id);
create index if not exists idx_audit_logs_created_at on public.audit_logs (created_at desc);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at
before update on public.categories
for each row execute function public.touch_updated_at();

drop trigger if exists trg_packages_updated_at on public.question_packages;
create trigger trg_packages_updated_at
before update on public.question_packages
for each row execute function public.touch_updated_at();

drop trigger if exists trg_questions_updated_at on public.questions;
create trigger trg_questions_updated_at
before update on public.questions
for each row execute function public.touch_updated_at();

drop trigger if exists trg_assignments_updated_at on public.assignments;
create trigger trg_assignments_updated_at
before update on public.assignments
for each row execute function public.touch_updated_at();

drop trigger if exists trg_attempts_updated_at on public.attempts;
create trigger trg_attempts_updated_at
before update on public.attempts
for each row execute function public.touch_updated_at();

drop trigger if exists trg_system_settings_updated_at on public.system_settings;
create trigger trg_system_settings_updated_at
before update on public.system_settings
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, username, role, is_active, last_login_at)
  values (
    new.id,
    coalesce(new.email, ''),
    split_part(coalesce(new.email, 'user'), '@', 1),
    'student',
    true,
    now()
  )
  on conflict (id) do update
  set email = excluded.email,
      username = excluded.username,
      last_login_at = excluded.last_login_at;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.log_audit_event(
  p_action text,
  p_entity_type text,
  p_entity_id text default null,
  p_summary text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (actor_id, action, entity_type, entity_id, summary, metadata)
  values (auth.uid(), p_action, p_entity_type, p_entity_id, p_summary, coalesce(p_metadata, '{}'::jsonb));
end;
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.question_packages enable row level security;
alter table public.questions enable row level security;
alter table public.assignments enable row level security;
alter table public.attempts enable row level security;
alter table public.attempt_answers enable row level security;
alter table public.system_settings enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin_like());

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id or public.is_admin_like());

drop policy if exists "profiles_update_self_or_admin" on public.profiles;
create policy "profiles_update_self_or_admin"
on public.profiles
for update
to authenticated
using (id = auth.uid() or public.is_admin_like())
with check (id = auth.uid() or public.is_admin_like());

drop policy if exists "profiles_delete_superadmin" on public.profiles;
create policy "profiles_delete_superadmin"
on public.profiles
for delete
to authenticated
using (public.is_superadmin());

drop policy if exists "categories_select_authenticated" on public.categories;
create policy "categories_select_authenticated"
on public.categories
for select
to authenticated
using (true);

drop policy if exists "categories_write_admin" on public.categories;
create policy "categories_write_admin"
on public.categories
for all
to authenticated
using (public.is_admin_like())
with check (public.is_admin_like());

drop policy if exists "packages_select_access" on public.question_packages;
create policy "packages_select_access"
on public.question_packages
for select
to authenticated
using (
  public.is_admin_like()
  or (
    is_published
    and public.student_package_access(id)
  )
);

drop policy if exists "packages_write_admin" on public.question_packages;
create policy "packages_write_admin"
on public.question_packages
for all
to authenticated
using (public.is_admin_like())
with check (public.is_admin_like());

drop policy if exists "questions_select_access" on public.questions;
create policy "questions_select_access"
on public.questions
for select
to authenticated
using (
  public.is_admin_like()
  or public.student_question_access(package_id)
);

drop policy if exists "questions_write_admin" on public.questions;
create policy "questions_write_admin"
on public.questions
for all
to authenticated
using (public.is_admin_like())
with check (public.is_admin_like());

drop policy if exists "assignments_select_access" on public.assignments;
create policy "assignments_select_access"
on public.assignments
for select
to authenticated
using (
  public.is_admin_like()
  or assigned_to_user = auth.uid()
  or exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and assigned_to_class is not null
      and p.class_name is not null
      and lower(assigned_to_class) = lower(p.class_name)
  )
);

drop policy if exists "assignments_write_admin" on public.assignments;
create policy "assignments_write_admin"
on public.assignments
for all
to authenticated
using (public.is_admin_like())
with check (public.is_admin_like());

drop policy if exists "attempts_select_access" on public.attempts;
create policy "attempts_select_access"
on public.attempts
for select
to authenticated
using (public.is_admin_like() or user_id = auth.uid());

drop policy if exists "attempts_insert_own" on public.attempts;
create policy "attempts_insert_own"
on public.attempts
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "attempts_update_own_or_admin" on public.attempts;
create policy "attempts_update_own_or_admin"
on public.attempts
for update
to authenticated
using (public.is_admin_like() or user_id = auth.uid())
with check (public.is_admin_like() or user_id = auth.uid());

drop policy if exists "attempt_answers_select_access" on public.attempt_answers;
create policy "attempt_answers_select_access"
on public.attempt_answers
for select
to authenticated
using (
  public.is_admin_like()
  or exists (
    select 1
    from public.attempts a
    where a.id = attempt_id
      and a.user_id = auth.uid()
  )
);

drop policy if exists "attempt_answers_insert_own" on public.attempt_answers;
create policy "attempt_answers_insert_own"
on public.attempt_answers
for insert
to authenticated
with check (
  exists (
    select 1
    from public.attempts a
    where a.id = attempt_id
      and a.user_id = auth.uid()
  )
);

drop policy if exists "attempt_answers_update_admin" on public.attempt_answers;
create policy "attempt_answers_update_admin"
on public.attempt_answers
for update
to authenticated
using (public.is_admin_like())
with check (public.is_admin_like());

drop policy if exists "system_settings_select_authenticated" on public.system_settings;
create policy "system_settings_select_authenticated"
on public.system_settings
for select
to authenticated
using (true);

drop policy if exists "system_settings_write_superadmin" on public.system_settings;
create policy "system_settings_write_superadmin"
on public.system_settings
for all
to authenticated
using (public.is_superadmin())
with check (public.is_superadmin());

drop policy if exists "audit_logs_select_superadmin" on public.audit_logs;
create policy "audit_logs_select_superadmin"
on public.audit_logs
for select
to authenticated
using (public.is_superadmin());

drop policy if exists "audit_logs_insert_admin" on public.audit_logs;
create policy "audit_logs_insert_admin"
on public.audit_logs
for insert
to authenticated
with check (public.is_admin_like() or public.is_superadmin());

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.categories to authenticated;
grant select, insert, update, delete on public.question_packages to authenticated;
grant select, insert, update, delete on public.questions to authenticated;
grant select, insert, update, delete on public.assignments to authenticated;
grant select, insert, update, delete on public.attempts to authenticated;
grant select, insert, update, delete on public.attempt_answers to authenticated;
grant select, insert, update, delete on public.system_settings to authenticated;
grant select, insert on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.system_settings (key, value)
values
  ('app_name', 'Bimbel Juara CBT'),
  ('maintenance_mode', 'false'),
  ('default_exam_duration_minutes', '60'),
  ('default_passing_score', '70'),
  ('announcement', 'Selamat datang di CBT Bimbel Juara')
on conflict (key) do nothing;
